/* cspell: disable */
/**
 * Seeder: School Data
 *
 * source:
 *  https://www.edb.gov.hk/en/edu-system/primary-secondary/spa-systems/secondary-spa/general-info/secondary-sch-list.html
 */

import type { Locale } from '@argonne/common';

type SchoolData = {
  district: string;
  code: string;
  name: Locale;
  phones?: string[];
  levels?: string[];
  website?: string;
};

export const internationalSchools: SchoolData[] = [];

export const primarySchools: SchoolData[] = [];

export const secondarySchools: SchoolData[] = [
  {
    district: '南區',
    code: '101',
    name: { enUS: 'CARITAS WU CHENG-CHUNG SECONDARY SCHOOL', zhHK: '明愛胡振中中學' },
    phones: ['+852 22937708', '+852 28172318'],
  },
  {
    district: 'Central & Western',
    code: '103',
    name: { enUS: "KING'S COLLEGE", zhHK: '英皇書院', zhCN: '英往书院' },
    phones: ['+852 25470310'],
  },
  {
    district: '中西區',
    code: '104',
    name: { enUS: 'LOK SIN TONG LEUNG KAU KUI COLLEGE', zhHK: '樂善堂梁銶琚書院', zhCN: '乐善堂梁銶琚书院' },
    phones: ['+852 28587002'],
  },
  {
    district: '中西區',
    code: '105',
    name: { enUS: 'RAIMONDI COLLEGE', zhHK: '高主教書院', zhCN: '高主教书院' },
    phones: ['+852 28587002'],
  },
  {
    district: '中西區',
    code: '107',
    name: { enUS: "ST CLARE'S GIRLS' SCHOOL", zhHK: '聖嘉勒女書院' },
    phones: ['+852 28171764'],
  },
  {
    district: '中西區',
    code: '108',
    name: { enUS: "ST JOSEPH'S COLLEGE", zhHK: '聖若瑟書院' },
    phones: ['+852 36524888'],
  },
  {
    district: '中西區',
    code: '109',
    name: { enUS: 'ST LOUIS SCHOOL', zhHK: '聖類斯中學' },
    phones: ['+852 25460117'],
  },

  {
    district: '中西區',
    code: '112',
    name: { enUS: "ST STEPHEN'S CHURCH COLLEGE", zhHK: '聖士提反堂中學' },
    phones: ['+852 25466111'],
  },

  {
    district: '中西區',
    code: '113',
    name: { enUS: "ST STEPHEN'S GIRLS' COLLEGE", zhHK: '聖士提反女子中學' },
    phones: ['+852 25492521'],
  },

  {
    district: '中西區',
    code: '114',
    name: { enUS: "YING WA GIRLS' SCHOOL", zhHK: '英華女學校' },
    phones: ['+852 25463151'],
  },

  {
    district: '灣仔區',
    code: '115',
    name: { enUS: 'BUDDHIST WONG FUNG LING COLLEGE', zhHK: '佛教黃鳳翎中學' },
    phones: ['+852 25779485'],
  },
  {
    district: '灣仔區',
    code: '117',
    name: { enUS: 'HOTUNG SECONDARY SCHOOL', zhHK: '何東中學' },
    phones: ['+852 25775433'],
  },
  {
    district: '灣仔區',
    code: '119',
    name: { enUS: 'HONG KONG TANG KING PO COLLEGE', zhHK: '香港鄧鏡波書院' },
    phones: ['+852 25272427'],
  },
  {
    district: '東區',
    code: '121',
    name: { enUS: 'LINGNAN SECONDARY SCHOOL', zhHK: '嶺南中學' },
    phones: ['+852 28916966'],
  },
  {
    district: '灣仔區',
    code: '122',
    name: { enUS: 'MARYMOUNT SECONDARY SCHOOL', zhHK: '瑪利曼中學' },
    phones: ['+852 25728221'],
  },
  {
    district: '灣仔區',
    code: '124',
    name: { enUS: "QUEEN'S COLLEGE", zhHK: '皇仁書院' },
    phones: ['+852 25761992'],
  },
  {
    district: '灣仔區',
    code: '125',
    name: { enUS: 'ROSARYHILL SECONDARY SCHOOL', zhHK: '玫瑰崗中學' },
    phones: ['+852 28355127'],
  },
  {
    district: '灣仔區',
    code: '126',
    name: { enUS: 'SKH TANG SHIU KIN SECONDARY SCHOOL', zhHK: '聖公會鄧肇堅中學' },
    phones: ['+852 25742326'],
  },
  {
    district: '灣仔區',
    code: '127',
    name: { enUS: "ST FRANCIS' CANOSSIAN COLLEGE", zhHK: '嘉諾撒聖方濟各書院' },
    phones: ['+852 25872700'],
  },
  {
    district: '深水埗區',
    code: '129',
    name: { enUS: "SKH ST MARY'S CHURCH MOK HING YIU COLLEGE", zhHK: '聖公會聖馬利亞堂莫慶堯中學' },
    phones: ['+852 25779559'],
  },
  {
    district: '灣仔區',
    code: '131',
    name: { enUS: "ST PAUL'S SECONDARY SCHOOL", zhHK: '聖保祿中學' },
    phones: ['+852 25773837'],
  },
  {
    district: '灣仔區',
    code: '132',
    name: { enUS: 'TANG SHIU KIN VICTORIA GOVERNMENT SECONDARY SCHOOL', zhHK: '鄧肇堅維多利亞官立中學' },
    phones: ['+852 25736962'],
  },
  {
    district: '灣仔區',
    code: '134',
    name: { enUS: 'TRUE LIGHT MIDDLE SCHOOL OF HONG KONG', zhHK: '香港真光中學' },
    phones: ['+852 25760703'],
  },
  {
    district: '灣仔區',
    code: '135',
    name: { enUS: 'WAH YAN COLLEGE, HONG KONG', zhHK: '香港華仁書院' },
    phones: ['+852 25722251'],
  },
  {
    district: '東區',
    code: '136',
    name: { enUS: 'BELILIOS PUBLIC SCHOOL', zhHK: '庇理羅士女子中學' },
    phones: ['+852 25718018'],
  },
  {
    district: '東區',
    code: '137',
    name: { enUS: 'CCC KWEI WAH SHAN COLLEGE', zhHK: '中華基督教會桂華山中學' },
    phones: ['+852 25711285'],
  },
  {
    district: '東區',
    code: '138',
    name: { enUS: 'CANOSSA COLLEGE', zhHK: '嘉諾撒書院' },
    phones: ['+852 25630272'],
  },
  {
    district: '東區',
    code: '139',
    name: { enUS: 'CHEUNG CHUK SHAN COLLEGE', zhHK: '張祝珊英文中學' },
    phones: ['+852 25706665'],
  },
  {
    district: '東區',
    code: '140',
    name: { enUS: 'CHONG GENE HANG COLLEGE', zhHK: '張振興伉儷書院' },
    phones: ['+852 25566081'],
  },
  {
    district: '東區',
    code: '141',
    name: { enUS: 'CLEMENTI SECONDARY SCHOOL', zhHK: '金文泰中學' },
    phones: ['+852 25706411'],
  },
  {
    district: '東區',
    code: '142',
    name: { enUS: 'COGNITIO COLLEGE (HONG KONG)', zhHK: '文理書院（香港）' },
    phones: ['+852 25567413'],
  },
  {
    district: '灣仔區',
    code: '143',
    name: { enUS: 'CONCORDIA LUTHERAN SCHOOL - NORTH POINT', zhHK: '北角協同中學' },
    phones: ['+852 25700331', '+852 25700332', '+852 25700333'],
  },
  {
    district: '東區',
    code: '144',
    name: { enUS: 'HENRIETTA SECONDARY SCHOOL', zhHK: '顯理中學' },
    phones: ['+852 25701466'],
  },
  {
    district: '東區',
    code: '146',
    name: { enUS: "HONG KONG CHINESE WOMEN'S CLUB COLLEGE", zhHK: '香港中國婦女會中學' },
    phones: ['+852 25684817'],
  },
  {
    district: '東區',
    code: '148',
    name: { enUS: 'LINGNAN HANG YEE MEMORIAL SECONDARY SCHOOL', zhHK: '嶺南衡怡紀念中學' },
    phones: ['+852 25764852'],
  },
  {
    district: '東區',
    code: '149',
    name: { enUS: 'MAN KIU COLLEGE', zhHK: '閩僑中學' },
    phones: ['+852 25784523'],
  },
  {
    district: '東區',
    code: '150',
    name: { enUS: 'CARITAS CHAI WAN MARDEN FOUNDATION SECONDARY SCHOOL', zhHK: '明愛柴灣馬登基金中學' },
    phones: ['+852 25584133'],
  },
  {
    district: '東區',
    code: '151',
    name: { enUS: 'PRECIOUS BLOOD SECONDARY SCHOOL', zhHK: '寶血女子中學' },
    phones: ['+852 25704172'],
  },
  {
    district: '東區',
    code: '152',
    name: { enUS: 'SKH LI FOOK HING SECONDARY SCHOOL', zhHK: '聖公會李福慶中學' },
    phones: ['+852 25704172'],
  },
  {
    district: '東區',
    code: '153',
    name: { enUS: 'SALESIAN ENGLISH SCHOOL', zhHK: '慈幼英文學校' },
    phones: ['+852 28843581'],
  },
  {
    district: '東區',
    code: '154',
    name: { enUS: 'SHAU KEI WAN GOVERNMENT SECONDARY SCHOOL', zhHK: '筲箕灣官立中學' },
    phones: ['+852 25603544'],
  },
  {
    district: '東區',
    code: '155',
    name: { enUS: 'SHAU KEI WAN EAST GOVERNMENT SECONDARY SCHOOL', zhHK: '筲箕灣東官立中學' },
    phones: ['+852 25602677'],
  },
  {
    district: '東區',
    code: '157',
    name: { enUS: 'ST JOAN OF ARC SECONDARY SCHOOL', zhHK: '聖貞德中學' },
    phones: ['+852 25785984'],
  },
  {
    district: '東區',
    code: '158',
    name: { enUS: "ST MARK'S SCHOOL", zhHK: '聖馬可中學' },
    phones: ['+852 25601262'],
  },
  {
    district: '灣仔區',
    code: '159',
    name: { enUS: 'TWGH LEE CHING DEA MEMORIAL COLLEGE', zhHK: '東華三院李潤田紀念中學' },
    phones: ['+852 25715422'],
  },
  {
    district: '東區',
    code: '160',
    name: { enUS: 'THE METHODIST CHURCH HK WESLEY COLLEGE', zhHK: '衞理中學' },
    phones: ['+852 28967705'],
  },
  {
    district: '南區',
    code: '161',
    name: { enUS: 'ABERDEEN BAPTIST LUI MING CHOI COLLEGE', zhHK: '香港仔浸信會呂明才書院' },
    phones: ['+852 25526875'],
  },
  {
    district: '南區',
    code: '162',
    name: { enUS: 'ABERDEEN TECHNICAL SCHOOL', zhHK: '香港仔工業學校' },
    phones: ['+852 25524141'],
  },
  {
    district: '南區',
    code: '163',
    name: { enUS: 'CARITAS CHONG YUET MING SECONDARY SCHOOL', zhHK: '明愛莊月明中學' },
    phones: ['+852 25510200'],
  },
  {
    district: '南區',
    code: '165',
    name: { enUS: 'HONG KONG TRUE LIGHT COLLEGE', zhHK: '香港真光書院' },
    phones: ['+852 28711214'],
  },
  {
    district: '南區',
    code: '166',
    name: { enUS: 'PUI TAK CANOSSIAN COLLEGE', zhHK: '嘉諾撒培德書院' },
    phones: ['+852 25540780'],
  },
  {
    district: '南區',
    code: '167',
    name: { enUS: 'PUI YING SECONDARY SCHOOL', zhHK: '培英中學' },
    phones: ['+852 25503632'],
  },
  {
    district: '南區',
    code: '169',
    name: { enUS: 'SKH LUI MING CHOI SECONDARY SCHOOL', zhHK: '聖公會呂明才中學' },
    phones: ['+852 25514121'],
  },
  {
    district: '南區',
    code: '170',
    name: { enUS: 'SACRED HEART CANOSSIAN COLLEGE', zhHK: '嘉諾撒聖心書院' },
    phones: ['+852 25506111'],
  },
  {
    district: '南區',
    code: '171',
    name: { enUS: 'SAN WUI COMMERCIAL SOCIETY CHAN PAK SHA SCHOOL', zhHK: '新會商會陳白沙紀念中學' },
    phones: ['+852 25535324'],
  },
  {
    district: '南區',
    code: '173',
    name: { enUS: "ST PETER'S SECONDARY SCHOOL", zhHK: '聖伯多祿中學' },
    phones: ['+852 25520080'],
  },
  {
    district: '南區',
    code: '175',
    name: { enUS: 'YU CHUN KEUNG MEMORIAL COLLEGE NO.2', zhHK: '余振強紀念第二中學' },
    phones: ['+852 25518285'],
  },
  {
    district: '油尖旺區',
    code: '177',
    name: { enUS: 'HK & KLN CHIU CHOW PUBLIC ASSN SECONDARY SCHOOL', zhHK: '港九潮州公會中學' },
    phones: ['+852 23964187'],
  },
  {
    district: '油尖旺區',
    code: '178',
    name: { enUS: 'KOWLOON SAM YUK SECONDARY SCHOOL', zhHK: '九龍三育中學' },
    phones: ['+852 23973181'],
  },
  {
    district: '油尖旺區',
    code: '179',
    name: { enUS: 'LAI CHACK MIDDLE SCHOOL', zhHK: '麗澤中學' },
    phones: ['+852 27213086'],
  },
  {
    district: '油尖旺區',
    code: '180',
    name: { enUS: 'LKWFSL LAU WONG FAT SECONDARY SCHOOL', zhHK: '世界龍岡學校劉皇發中學' },
    phones: ['+852 23944186'],
  },
  {
    district: '油尖旺區',
    code: '181',
    name: { enUS: 'ELCHK LUTHERAN SECONDARY SCHOOL', zhHK: '基督教香港信義會信義中學' },
    phones: ['+852 27802291'],
  },
  {
    district: '油尖旺區',
    code: '182',
    name: { enUS: 'METHODIST COLLEGE', zhHK: '循道中學' },
    phones: ['+852 23843543'],
  },
  {
    district: '油尖旺區',
    code: '183',
    name: { enUS: 'CCC MING KEI COLLEGE', zhHK: '中華基督教會銘基書院' },
    phones: ['+852 23923963'],
  },
  {
    district: '油尖旺區',
    code: '184',
    name: { enUS: 'NEWMAN CATHOLIC COLLEGE', zhHK: '天主教新民書院' },
    phones: ['+852 23857812'],
  },
  {
    district: '油尖旺區',
    code: '185',
    name: { enUS: 'QUEEN ELIZABETH SCHOOL', zhHK: '伊利沙伯中學' },
    phones: ['+852 23809621'],
  },
  {
    district: '油尖旺區',
    code: '186',
    name: { enUS: "SKH ALL SAINTS' MIDDLE SCHOOL", zhHK: '聖公會諸聖中學' },
    phones: ['+852 27800147'],
  },
  {
    district: '油尖旺區',
    code: '187',
    name: { enUS: "ST FRANCIS XAVIER'S COLLEGE", zhHK: '聖芳濟書院' },
    phones: ['+852 23932271'],
  },
  {
    district: '油尖旺區',
    code: '189',
    name: { enUS: "ST MARY'S CANOSSIAN COLLEGE", zhHK: '嘉諾撒聖瑪利書院' },
    phones: ['+852 27242771'],
  },
  {
    district: '油尖旺區',
    code: '190',
    name: { enUS: "TRUE LIGHT GIRLS' COLLEGE", zhHK: '真光女書院' },
    phones: ['+852 23851491'],
  },
  {
    district: '油尖旺區',
    code: '191',
    name: { enUS: 'WAH YAN COLLEGE, KOWLOON', zhHK: '華仁書院（九龍）' },
    phones: ['+852 23841038'],
  },
  {
    district: '深水埗區',
    code: '192',
    name: { enUS: 'BUDDHIST TAI HUNG COLLEGE', zhHK: '佛教大雄中學' },
    phones: ['+852 23862988'],
  },
  {
    district: '深水埗區',
    code: '194',
    name: { enUS: 'CHEUNG SHA WAN CATHOLIC SECONDARY SCHOOL', zhHK: '長沙灣天主教英文中學' },
    phones: ['+852 27415034'],
  },
  {
    district: '深水埗區',
    code: '195',
    name: { enUS: 'CHINA HOLINESS COLLEGE', zhHK: '中聖書院' },
    phones: ['+852 23864734'],
  },
  {
    district: '深水埗區',
    code: '196',
    name: { enUS: 'CMA SECONDARY SCHOOL', zhHK: '廠商會中學' },
    phones: ['+852 27796851'],
  },
  {
    district: '深水埗區',
    code: '197',
    name: { enUS: 'CONCORDIA LUTHERAN SCHOOL', zhHK: '路德會協同中學' },
    phones: ['+852 23808837'],
  },
  {
    district: '深水埗區',
    code: '200',
    name: { enUS: 'HKSYC&IA WONG TAI SHAN MEMORIAL COLLEGE', zhHK: '香港四邑商工總會黃棣珊紀念中學' },
    phones: ['+852 27788982'],
  },
  {
    district: '深水埗區',
    code: '201',
    name: { enUS: 'HOLY TRINITY COLLEGE', zhHK: '寶血會上智英文書院' },
    phones: ['+852 27793220'],
  },
  {
    district: '深水埗區',
    code: '202',
    name: { enUS: 'KOWLOON TECHNICAL SCHOOL', zhHK: '九龍工業學校' },
    phones: ['+852 23860737'],
  },
  {
    district: '深水埗區',
    code: '203',
    name: { enUS: "MARYKNOLL FATHERS' SCHOOL", zhHK: '瑪利諾神父教會學校' },
    phones: ['+852 27775117'],
  },
  {
    district: '深水埗區',
    code: '204',
    name: { enUS: 'CCC MING YIN COLLEGE', zhHK: '中華基督教會銘賢書院' },
    phones: ['+852 27784512'],
  },
  {
    district: '深水埗區',
    code: '205',
    name: { enUS: 'NAM WAH CATHOLIC SECONDARY SCHOOL', zhHK: '天主教南華中學' },
    phones: ['+852 27411174'],
  },
  {
    district: '深水埗區',
    code: '206',
    name: { enUS: 'OUR LADY OF THE ROSARY COLLEGE', zhHK: '聖母玫瑰書院' },
    phones: ['+852 23806468'],
  },
  {
    district: '深水埗區',
    code: '209',
    name: { enUS: 'TWGH CHANG MING THIEN COLLEGE', zhHK: '東華三院張明添中學' },
    phones: ['+852 27792986'],
  },
  {
    district: '深水埗區',
    code: '210',
    name: { enUS: "TACK CHING GIRLS' SECONDARY SCHOOL", zhHK: '德貞女子中學' },
    phones: ['+852 27293211'],
  },
  {
    district: '深水埗區',
    code: '211',
    name: { enUS: 'TAK NGA SECONDARY SCHOOL', zhHK: '德雅中學' },
    phones: ['+852 23814483', '+852 23803788'],
  },
  {
    district: '深水埗區',
    code: '213',
    name: { enUS: 'UNITED CHRISTIAN COLLEGE', zhHK: '滙基書院' },
    phones: ['+852 27778344'],
  },
  {
    district: '深水埗區',
    code: '214',
    name: { enUS: 'WAI KIU COLLEGE', zhHK: '惠僑英文中學' },
    phones: ['+852 27776289'],
  },
  {
    district: '葵青區',
    code: '215',
    name: { enUS: 'CCC YENCHING COLLEGE', zhHK: '中華基督教會燕京書院' },
    phones: ['+852 23879988'],
  },
  {
    district: '九龍城區',
    code: '217',
    name: { enUS: 'CARMEL SECONDARY SCHOOL', zhHK: '迦密中學' },
    phones: ['+852 27149385'],
  },
  {
    district: '九龍城區',
    code: '218',
    name: { enUS: 'CHAN SUI KI (LA SALLE) COLLEGE', zhHK: '陳瑞祺（喇沙）書院' },
    phones: ['+852 27118175'],
  },
  {
    district: '九龍城區',
    code: '221',
    name: { enUS: 'HOI PING CHAMBER OF COMMERCE SECONDARY SCHOOL', zhHK: '旅港開平商會中學' },
    phones: ['+852 27123107'],
  },
  {
    district: '九龍城區',
    code: '222',
    name: { enUS: 'SKH HOLY CARPENTER SECONDARY SCHOOL', zhHK: '聖公會聖匠中學' },
    phones: ['+852 23642730'],
  },
  {
    district: '九龍城區',
    code: '223',
    name: { enUS: 'HOLY FAMILY CANOSSIAN COLLEGE', zhHK: '嘉諾撒聖家書院' },
    phones: ['+852 23379123'],
  },
  {
    district: '九龍城區',
    code: '224',
    name: { enUS: 'HOMANTIN GOVERNMENT SECONDARY SCHOOL', zhHK: '何文田官立中學' },
    phones: ['+852 27112680'],
  },
  {
    district: '九龍城區',
    code: '225',
    name: { enUS: 'JOCKEY CLUB GOVERNMENT SECONDARY SCHOOL', zhHK: '賽馬會官立中學' },
    phones: ['+852 23366761'],
  },
  {
    district: '九龍城區',
    code: '226',
    name: { enUS: 'KOWLOON TONG SCHOOL (SECONDARY SECTION)', zhHK: '九龍塘學校（中學部）' },
    phones: ['+852 23370680'],
  },
  {
    district: '九龍城區',
    code: '227',
    name: { enUS: 'KOWLOON TRUE LIGHT SCHOOL', zhHK: '九龍真光中學' },
    phones: ['+852 36550000'],
  },
  {
    district: '九龍城區',
    code: '228',
    name: { enUS: 'LA SALLE COLLEGE', zhHK: '喇沙書院' },
    phones: ['+852 23387171'],
  },
  {
    district: '九龍城區',
    code: '229',
    name: { enUS: 'MARYKNOLL CONVENT SCHOOL (SECONDARY SECTION)', zhHK: '瑪利諾修院學校（中學部）' },
    phones: ['+852 23362378'],
  },
  {
    district: '九龍城區',
    code: '230',
    name: { enUS: 'MUNSANG COLLEGE', zhHK: '民生書院' },
    phones: ['+852 36553328'],
  },
  {
    district: '九龍城區',
    code: '231',
    name: { enUS: 'NEW ASIA MIDDLE SCHOOL', zhHK: '新亞中學' },
    phones: ['+852 27112206'],
  },
  {
    district: '九龍城區',
    code: '233',
    name: { enUS: 'NOTRE DAME COLLEGE', zhHK: '獻主會聖母院書院' },
    phones: ['+852 27115291'],
  },
  {
    district: '九龍城區',
    code: '234',
    name: { enUS: 'PENTECOSTAL SCHOOL', zhHK: '五旬節中學' },
    phones: ['+852 27132772'],
  },
  {
    district: '九龍城區',
    code: '235',
    name: { enUS: 'POOI TO MIDDLE SCHOOL', zhHK: '香港培道中學' },
    phones: ['+852 23361706'],
  },
  {
    district: '九龍城區',
    code: '236',
    name: { enUS: 'PUI CHING MIDDLE SCHOOL', zhHK: '香港培正中學' },
    phones: ['+852 27119222'],
  },
  {
    district: '九龍城區',
    code: '237',
    name: { enUS: 'RHENISH CHURCH PANG HOK-KO MEMORIAL COLLEGE', zhHK: '禮賢會彭學高紀念中學' },
    phones: ['+852 23370283'],
  },
  {
    district: '九龍城區',
    code: '238',
    name: { enUS: 'SKH HOLY TRINITY CHURCH SECONDARY SCHOOL', zhHK: '聖公會聖三一堂中學' },
    phones: ['+852 27144137'],
  },
  {
    district: '九龍城區',
    code: '239',
    name: { enUS: 'SKH TSOI KUNG PO SECONDARY SCHOOL', zhHK: '聖公會蔡功譜中學' },
    phones: ['+852 27600463'],
  },
  {
    district: '沙田區',
    code: '240',
    name: { enUS: "ST ROSE OF LIMA'S COLLEGE", zhHK: '聖羅撒書院' },
    phones: ['+852 23371867'],
  },
  {
    district: '九龍城區',
    code: '241',
    name: { enUS: 'ST TERESA SECONDARY SCHOOL', zhHK: '德蘭中學' },
    phones: ['+852 27115202'],
  },
  {
    district: '九龍城區',
    code: '242',
    name: { enUS: 'STFA SEAWARD WOO COLLEGE', zhHK: '順德聯誼總會胡兆熾中學' },
    phones: ['+852 27621183'],
  },
  {
    district: '九龍城區',
    code: '243',
    name: { enUS: 'TWGH WONG FUT NAM COLLEGE', zhHK: '東華三院黃笏南中學' },
    phones: ['+852 23369151'],
  },
  {
    district: '九龍城區',
    code: '244',
    name: { enUS: 'TANG KING PO SCHOOL', zhHK: '鄧鏡波學校' },
    phones: ['+852 27125171'],
  },
  {
    district: '九龍城區',
    code: '245',
    name: { enUS: 'BISHOP HALL JUBILEE SCHOOL', zhHK: '何明華會督銀禧中學' },
    phones: ['+852 23363034'],
  },
  {
    district: '九龍城區',
    code: '246',
    name: { enUS: 'THE YWCA HIOE TJO YOENG COLLEGE', zhHK: '基督教女青年會丘佐榮中學' },
    phones: ['+852 27117159'],
  },
  {
    district: '九龍城區',
    code: '247',
    name: { enUS: 'WA YING COLLEGE', zhHK: '華英中學' },
    phones: ['+852 27607772'],
  },
  {
    district: '九龍城區',
    code: '249',
    name: { enUS: 'YU CHUN KEUNG MEMORIAL COLLEGE', zhHK: '余振強紀念中學' },
    phones: ['+852 27144161'],
  },
  {
    district: '黃大仙區',
    code: '250',
    name: { enUS: 'BUDDHIST HUNG SEAN CHAU MEMORIAL COLLEGE', zhHK: '佛教孔仙洲紀念中學' },
    phones: ['+852 23226915'],
  },
  {
    district: '黃大仙區',
    code: '251',
    name: { enUS: 'CCC ROTARY SECONDARY SCHOOL', zhHK: '中華基督教會扶輪中學' },
    phones: ['+852 23381971'],
  },
  {
    district: '黃大仙區',
    code: '252',
    name: { enUS: 'CHOI HUNG ESTATE CATHOLIC SECONDARY SCHOOL', zhHK: '彩虹邨天主教英文中學' },
    phones: ['+852 23203594'],
  },
  {
    district: '九龍城區',
    code: '253',
    name: { enUS: 'COGNITIO COLLEGE (KOWLOON)', zhHK: '文理書院（九龍）' },
    phones: ['+852 23231741'],
  },
  {
    district: '黃大仙區',
    code: '255',
    name: { enUS: 'CCC HEEP WOH COLLEGE', zhHK: '中華基督教會協和書院' },
    phones: ['+852 23234265'],
  },
  {
    district: '黃大仙區',
    code: '256',
    name: { enUS: 'HO LAP COLLEGE (SPSD BY THE SIK SIK YUEN)', zhHK: '可立中學（嗇色園主辦）' },
    phones: ['+852 23215525', '+852 23222229'],
  },
  {
    district: '黃大仙區',
    code: '257',
    name: { enUS: 'CCC KEI HEEP SECONDARY SCHOOL', zhHK: '中華基督教會基協中學' },
    phones: ['+852 23204557'],
  },
  {
    district: '黃大仙區',
    code: '258',
    name: { enUS: 'KIT SAM LAM BING YIM SECONDARY SCHOOL', zhHK: '潔心林炳炎中學' },
    phones: ['+852 23379594'],
  },
  {
    district: '黃大仙區',
    code: '259',
    name: { enUS: 'LEE KAU YAN MEMORIAL SCHOOL', zhHK: '李求恩紀念中學' },
    phones: ['+852 23834815'],
  },
  {
    district: '黃大仙區',
    code: '260',
    name: { enUS: 'LOK SIN TONG WONG CHUNG MING SECONDARY SCHOOL', zhHK: '樂善堂王仲銘中學' },
    phones: ['+852 23820002'],
  },
  {
    district: '黃大仙區',
    code: '261',
    name: { enUS: 'LOK SIN TONG YU KAN HING SECONDARY SCHOOL', zhHK: '樂善堂余近卿中學' },
    phones: ['+852 23362657'],
  },
  {
    district: '黃大仙區',
    code: '262',
    name: { enUS: 'LUNG CHEUNG GOVERNMENT SECONDARY SCHOOL', zhHK: '龍翔官立中學' },
    phones: ['+852 23234202'],
  },
  {
    district: '黃大仙區',
    code: '263',
    name: { enUS: 'NG WAH CATHOLIC SECONDARY SCHOOL', zhHK: '天主教伍華中學' },
    phones: ['+852 23838077'],
  },
  {
    district: '黃大仙區',
    code: '264',
    name: { enUS: "OUR LADY'S COLLEGE", zhHK: '聖母書院' },
    phones: ['+852 23288631', '+852 23275860'],
  },
  {
    district: '黃大仙區',
    code: '265',
    name: { enUS: 'PLK NO.1 WH CHEUNG COLLEGE', zhHK: '保良局第一張永慶中學' },
    phones: ['+852 23212167'],
  },
  {
    district: '黃大仙區',
    code: '266',
    name: { enUS: 'STEWARDS POOI TUN SECONDARY SCHOOL', zhHK: '香港神託會培敦中學' },
    phones: ['+852 23265211'],
  },
  {
    district: '黃大仙區',
    code: '267',
    name: { enUS: "SHENG KUNG HUI ST BENEDICT'S SCHOOL", zhHK: '聖公會聖本德中學' },
    phones: ['+852 23200011'],
  },
  {
    district: '黃大仙區',
    code: '268',
    name: { enUS: 'ST BONAVENTURE COLLEGE & HIGH SCHOOL', zhHK: '聖文德書院' },
    phones: ['+852 23238217'],
  },
  {
    district: '黃大仙區',
    code: '269',
    name: { enUS: 'TAK OI SECONDARY SCHOOL', zhHK: '德愛中學' },
    phones: ['+852 23238504'],
  },
  {
    district: '黃大仙區',
    code: '270',
    name: { enUS: 'PHC WING KWONG COLLEGE', zhHK: '五旬節聖潔會永光書院' },
    phones: ['+852 23370137'],
  },
  {
    district: '黃大仙區',
    code: '271',
    name: { enUS: 'SALVATION ARMY WILLIAM BOOTH SECONDARY SCHOOL', zhHK: '救世軍卜維廉中學' },
    phones: ['+852 23269068'],
  },
  {
    district: '觀塘區',
    code: '272',
    name: { enUS: 'HK SKH BISHOP HALL SECONDARY SCHOOL', zhHK: '香港聖公會何明華會督中學' },
    phones: ['+852 23479224'],
  },
  {
    district: '觀塘區',
    code: '273',
    name: { enUS: 'BUDDHIST HO NAM KAM COLLEGE', zhHK: '佛教何南金中學' },
    phones: ['+852 23400871'],
  },
  {
    district: '觀塘區',
    code: '274',
    name: { enUS: 'CCC MONG MAN WAI COLLEGE', zhHK: '中華基督教會蒙民偉書院' },
    phones: ['+852 27276372'],
  },
  {
    district: '觀塘區',
    code: '277',
    name: { enUS: 'FDBWA SZETO HO SECONDARY SCHOOL', zhHK: '五邑司徒浩中學' },
    phones: ['+852 23405916'],
  },
  {
    district: '觀塘區',
    code: '278',
    name: { enUS: 'HKWMA CHU SHEK LUN SECONDARY SCHOOL', zhHK: '香港布廠商會朱石麟中學' },
    phones: ['+852 27968323'],
  },
  {
    district: '觀塘區',
    code: '279',
    name: { enUS: 'CCC KEI CHI SECONDARY SCHOOL', zhHK: '中華基督教會基智中學' },
    phones: ['+852 23422954'],
  },
  {
    district: '觀塘區',
    code: '280',
    name: { enUS: 'KO LUI SECONDARY SCHOOL', zhHK: '高雷中學' },
    phones: ['+852 23890213'],
  },
  {
    district: '觀塘區',
    code: '281',
    name: { enUS: 'KWUN TONG KUNG LOK GOVERNMENT SECONDARY SCHOOL', zhHK: '觀塘功樂官立中學' },
    phones: ['+852 23435059'],
  },
  {
    district: '觀塘區',
    code: '282',
    name: { enUS: 'KWUN TONG GOVERNMENT SECONDARY SCHOOL', zhHK: '觀塘官立中學' },
    phones: ['+852 23436220'],
  },
  {
    district: '觀塘區',
    code: '283',
    name: { enUS: 'KWUN TONG MARYKNOLL COLLEGE', zhHK: '觀塘瑪利諾書院' },
    phones: ['+852 27171485'],
  },
  {
    district: '觀塘區',
    code: '284',
    name: { enUS: 'LEUNG SHEK CHEE COLLEGE', zhHK: '梁式芝書院' },
    phones: ['+852 23496626'],
  },
  {
    district: '觀塘區',
    code: '285',
    name: { enUS: 'MARYKNOLL SECONDARY SCHOOL', zhHK: '瑪利諾中學' },
    phones: ['+852 27583102'],
  },
  {
    district: '觀塘區',
    code: '287',
    name: { enUS: 'MU KUANG ENGLISH SCHOOL', zhHK: '慕光英文書院' },
    phones: ['+852 23412932'],
  },
  {
    district: '觀塘區',
    code: '288',
    name: { enUS: 'NING PO COLLEGE', zhHK: '寧波公學' },
    phones: ['+852 23455633'],
  },
  {
    district: '觀塘區',
    code: '289',
    name: { enUS: 'NING PO NO.2 COLLEGE', zhHK: '寧波第二中學' },
    phones: ['+852 23467465'],
  },
  {
    district: '觀塘區',
    code: '290',
    name: { enUS: 'NLSI LUI KWOK PAT FONG COLLEGE', zhHK: '新生命教育協會呂郭碧鳳中學' },
    phones: ['+852 23480103'],
  },
  {
    district: '觀塘區',
    code: '292',
    name: { enUS: 'SKH KEI HAU SECONDARY SCHOOL', zhHK: '聖公會基孝中學' },
    phones: ['+852 23460252'],
  },
  {
    district: '觀塘區',
    code: '293',
    name: { enUS: 'SKH LEUNG KWAI YEE SECONDARY SCHOOL', zhHK: '聖公會梁季彜中學' },
    phones: ['+852 27274321'],
  },
  {
    district: '觀塘區',
    code: '294',
    name: { enUS: 'SHUN LEE CATHOLIC SECONDARY SCHOOL', zhHK: '順利天主教中學' },
    phones: ['+852 23893082'],
  },
  {
    district: '觀塘區',
    code: '295',
    name: { enUS: 'SING YIN SECONDARY SCHOOL', zhHK: '聖言中學' },
    phones: ['+852 23496281'],
  },
  {
    district: '觀塘區',
    code: '296',
    name: { enUS: "ST ANTONIUS GIRLS' COLLEGE", zhHK: '聖安當女書院' },
    phones: ['+852 23481379'],
  },
  {
    district: '觀塘區',
    code: '297',
    name: { enUS: "ST CATHARINE'S SCHOOL FOR GIRLS", zhHK: '聖傑靈女子中學' },
    phones: ['+852 23456481'],
  },
  {
    district: '觀塘區',
    code: '298',
    name: { enUS: "ST JOSEPH'S ANGLO-CHINESE SCHOOL", zhHK: '聖若瑟英文中學' },
    phones: ['+852 37524500'],
  },
  {
    district: '觀塘區',
    code: '299',
    name: { enUS: "ST PAUL'S SCHOOL (LAM TIN)", zhHK: '藍田聖保祿中學' },
    phones: ['+852 23472991'],
  },
  {
    district: '觀塘區',
    code: '300',
    name: { enUS: 'HKTA CHING CHUNG SECONDARY SCHOOL', zhHK: '香港道教聯合會青松中學' },
    phones: ['+852 27274315'],
  },
  {
    district: '觀塘區',
    code: '301',
    name: { enUS: 'MISSION COVENANT CHURCH HOLM GLAD COLLEGE', zhHK: '基督教聖約教會堅樂中學' },
    phones: ['+852 27274311'],
  },
  {
    district: '葵青區',
    code: '303',
    name: { enUS: 'BUDDHIST SIN TAK COLLEGE', zhHK: '佛教善德英文中學' },
    phones: ['+852 24212580'],
  },
  {
    district: '葵青區',
    code: '304',
    name: { enUS: 'BUDDHIST YIP KEI NAM MEMORIAL COLLEGE', zhHK: '佛教葉紀南紀念中學' },
    phones: ['+852 24953363'],
  },
  {
    district: '葵青區',
    code: '305',
    name: { enUS: 'CARITAS ST JOSEPH SECONDARY SCHOOL', zhHK: '明愛聖若瑟中學' },
    phones: ['+852 24331282'],
  },
  {
    district: '葵青區',
    code: '306',
    name: { enUS: 'CARMEL ALISON LAM FOUNDATION SECONDARY SCHOOL', zhHK: '迦密愛禮信中學' },
    phones: ['+852 27445117', '+852 36129177'],
  },
  {
    district: '葵青區',
    code: '307',
    name: { enUS: 'CCC CHUEN YUEN COLLEGE', zhHK: '中華基督教會全完中學' },
    phones: ['+852 24205050'],
  },
  {
    district: '葵青區',
    code: '308',
    name: { enUS: 'CNEC CHRISTIAN COLLEGE', zhHK: '中華傳道會安柱中學' },
    phones: ['+852 24230365'],
  },
  {
    district: '葵青區',
    code: '309',
    name: { enUS: 'COTTON SPINNERS ASSOCIATION SECONDARY SCHOOL', zhHK: '棉紡會中學' },
    phones: ['+852 24220028', '+852 24221669'],
  },
  {
    district: '葵青區',
    code: '310',
    name: { enUS: 'DMHC SIU MING CATHOLIC SECONDARY SCHOOL', zhHK: '天主教母佑會蕭明中學' },
    phones: ['+852 24241796'],
  },
  {
    district: '葵青區',
    code: '312',
    name: { enUS: 'HKSYC&IA CHAN NAM CHONG MEMORIAL COLLEGE', zhHK: '香港四邑商工總會陳南昌紀念中學' },
    phones: ['+852 27410326'],
  },
  {
    district: '葵青區',
    code: '313',
    name: { enUS: 'HKTA THE YUEN YUEN INST NO.1 SECONDARY SCHOOL', zhHK: '香港道教聯合會圓玄學院第一中學' },
    phones: ['+852 24271641'],
  },
  {
    district: '葵青區',
    code: '314',
    name: { enUS: 'JU CHING CHU SECONDARY SCHOOL (KWAI CHUNG)', zhHK: '裘錦秋中學（葵涌）' },
    phones: ['+852 24285858'],
  },
  {
    district: '葵青區',
    code: '315',
    name: { enUS: 'KIANGSU-CHEKIANG COLLEGE (KWAI CHUNG)', zhHK: '葵涌蘇浙公學' },
    phones: ['+852 24202103'],
  },
  {
    district: '葵青區',
    code: '316',
    name: { enUS: 'KWAI CHUNG METHODIST COLLEGE', zhHK: '葵涌循道中學' },
    phones: ['+852 27450010'],
  },
  {
    district: '葵青區',
    code: '317',
    name: { enUS: 'LAI KING CATHOLIC SECONDARY SCHOOL', zhHK: '荔景天主教中學' },
    phones: ['+852 27441610'],
  },
  {
    district: '葵青區',
    code: '318',
    name: { enUS: 'SKH LAM WOO MEMORIAL SECONDARY SCHOOL', zhHK: '聖公會林護紀念中學' },
    phones: ['+852 24208893'],
  },
  {
    district: '葵青區',
    code: '319',
    name: { enUS: 'CNEC LEE I YAO MEMORIAL SECONDARY SCHOOL', zhHK: '中華傳道會李賢堯紀念中學' },
    phones: ['+852 24204141'],
  },
  {
    district: '葵青區',
    code: '320',
    name: { enUS: 'LINGNAN DR CHUNG WING KWONG MEMORIAL SECONDARY SCHOOL', zhHK: '嶺南鍾榮光博士紀念中學' },
    phones: ['+852 27439488'],
  },
  {
    district: '葵青區',
    code: '321',
    name: { enUS: 'LIONS COLLEGE', zhHK: '獅子會中學' },
    phones: ['+852 26147938'],
  },
  {
    district: '葵青區',
    code: '322',
    name: { enUS: 'LOK SIN TONG KU CHIU MAN SECONDARY SCHOOL', zhHK: '樂善堂顧超文中學' },
    phones: ['+852 24295171'],
  },
  {
    district: '葵青區',
    code: '323',
    name: { enUS: 'LOK SIN TONG LEUNG CHIK WAI MEMORIAL SCHOOL', zhHK: '樂善堂梁植偉紀念中學' },
    phones: ['+852 24955890'],
  },
  {
    district: '葵青區',
    code: '324',
    name: { enUS: 'PLK LO KIT SING (1983) COLLEGE', zhHK: '保良局羅傑承（一九八三）中學' },
    phones: ['+852 24977110'],
  },
  {
    district: '葵青區',
    code: '325',
    name: { enUS: 'POPE PAUL VI COLLEGE', zhHK: '保祿六世書院' },
    phones: ['+852 24208575'],
  },
  {
    district: '葵青區',
    code: '326',
    name: { enUS: 'QCOBA SECONDARY SCHOOL', zhHK: '皇仁舊生會中學' },
    phones: ['+852 24975688'],
  },
  {
    district: '葵青區',
    code: '327',
    name: { enUS: 'SALESIANS OF DB NG SIU MUI SECONDARY SCHOOL', zhHK: '天主教慈幼會伍少梅中學' },
    phones: ['+852 24258223'],
  },
  {
    district: '葵青區',
    code: '328',
    name: { enUS: 'SHEK LEI CATHOLIC SECONDARY SCHOOL', zhHK: '石籬天主教中學' },
    phones: ['+852 24291221'],
  },
  {
    district: '葵青區',
    code: '331',
    name: { enUS: 'STFA LEE SHAU KEE COLLEGE', zhHK: '李惠利中學' },
    phones: ['+852 24294051'],
  },
  {
    district: '葵青區',
    code: '332',
    name: { enUS: 'TWGH CHEN ZAO MEN COLLEGE', zhHK: '東華三院陳兆民中學' },
    phones: ['+852 24245318'],
  },
  {
    district: '葵青區',
    code: '333',
    name: { enUS: 'TWGH MRS WU YORK YU MEMORIAL COLLEGE', zhHK: '東華三院伍若瑜夫人紀念中學' },
    phones: ['+852 24285129'],
  },
  {
    district: '葵青區',
    code: '334',
    name: { enUS: 'TWGH SC GAW MEMORIAL COLLEGE', zhHK: '東華三院吳祥川紀念中學' },
    phones: ['+852 24950226'],
  },
  {
    district: '葵青區',
    code: '335',
    name: { enUS: 'THE METHODIST LEE WAI LEE COLLEGE', zhHK: '順德聯誼總會李兆基中學' },
    phones: ['+852 24279121'],
  },
  {
    district: '荃灣區',
    code: '336',
    name: { enUS: 'HO FUNG COLLEGE (SPONSORED BY SIK SIK YUEN)', zhHK: '可風中學（嗇色園主辦）' },
    phones: ['+852 24253563'],
  },
  {
    district: '荃灣區',
    code: '337',
    name: { enUS: 'LIU PO SHAN MEMORIAL COLLEGE', zhHK: '廖寶珊紀念書院' },
    phones: ['+852 24996711'],
  },
  {
    district: '荃灣區',
    code: '338',
    name: { enUS: 'LUI MING CHOI LUTHERAN COLLEGE', zhHK: '路德會呂明才中學' },
    phones: ['+852 24920195'],
  },
  {
    district: '荃灣區',
    code: '339',
    name: { enUS: 'PLK LEE SHING PIK COLLEGE', zhHK: '保良局李城璧中學' },
    phones: ['+852 24983393'],
  },
  {
    district: '荃灣區',
    code: '340',
    name: { enUS: 'PLK YAO LING SUN COLLEGE', zhHK: '保良局姚連生中學' },
    phones: ['+852 24983331'],
  },
  {
    district: '荃灣區',
    code: '341',
    name: { enUS: 'PO ON COMM ASSN WONG SIU CHING SECONDARY SCHOOL', zhHK: '寶安商會王少清中學' },
    phones: ['+852 24140157'],
  },
  {
    district: '荃灣區',
    code: '342',
    name: { enUS: 'SKH LI PING SECONDARY SCHOOL', zhHK: '聖公會李炳中學' },
    phones: ['+852 24238806'],
  },
  {
    district: '荃灣區',
    code: '343',
    name: { enUS: "ST FRANCIS XAVIER'S SCHOOL, TSUEN WAN", zhHK: '荃灣聖芳濟中學' },
    phones: ['+852 24920226'],
  },
  {
    district: '荃灣區',
    code: '344',
    name: { enUS: 'TEXTILE INT ACC WOO HON FAI SECONDARY SCHOOL', zhHK: '紡織學會美國商會胡漢輝中學' },
    phones: ['+852 24908773'],
  },
  {
    district: '荃灣區',
    code: '345',
    name: { enUS: 'AD&FDPOHL LEUNG SING TAK COLLEGE', zhHK: '博愛醫院歷屆總理聯誼會梁省德中學' },
    phones: ['+852 24145151'],
  },
  {
    district: '荃灣區',
    code: '346',
    name: { enUS: 'TSUEN WAN GOVERNMENT SECONDARY SCHOOL', zhHK: '荃灣官立中學' },
    phones: ['+852 24903307'],
  },
  {
    district: '荃灣區',
    code: '347',
    name: { enUS: 'TSUEN WAN PUBLIC HO CHUEN YIU MEMORIAL COLLEGE', zhHK: '荃灣公立何傳耀紀念中學' },
    phones: ['+852 24966000'],
  },
  {
    district: '荃灣區',
    code: '348',
    name: { enUS: 'YCH LIM POR YEN SECONDARY SCHOOL', zhHK: '仁濟醫院林百欣中學' },
    phones: ['+852 24937258'],
  },
  {
    district: '屯門區',
    code: '349',
    name: { enUS: 'HHCKLA BUDDHIST LEUNG CHIK WAI COLLEGE', zhHK: '香海正覺蓮社佛教梁植偉中學' },
    phones: ['+852 24676672'],
  },
  {
    district: '屯門區',
    code: '350',
    name: { enUS: 'BUDDHIST SUM HEUNG LAM MEMORIAL COLLEGE', zhHK: '佛教沈香林紀念中學' },
    phones: ['+852 24623177'],
  },
  {
    district: '屯門區',
    code: '351',
    name: { enUS: 'CCC TAM LEE LAI FUN MEMORIAL SECONDARY SCHOOL', zhHK: '中華基督教會譚李麗芬紀念中學' },
    phones: ['+852 24522422'],
  },
  {
    district: '屯門區',
    code: '352',
    name: { enUS: 'CARMEL BUNNAN TONG MEMORIAL SECONDARY SCHOOL', zhHK: '迦密唐賓南紀念中學' },
    phones: ['+852 24651585'],
  },
  {
    district: '屯門區',
    code: '353',
    name: { enUS: 'CHRISTIAN ALLIANCE COLLEGE', zhHK: '宣道中學' },
    phones: ['+852 24692080'],
  },
  {
    district: '屯門區',
    code: '354',
    name: {
      enUS: 'CHRISTIAN ALLIANCE S C CHAN MEMORIAL COLLEGE',
      zhHK: '香港九龍塘基督教中華宣道會陳瑞芝紀念中學',
    },
    phones: ['+852 24591166'],
  },
  {
    district: '屯門區',
    code: '355',
    name: { enUS: 'CMA CHOI CHEUNG KOK SECONDARY SCHOOL', zhHK: '廠商會蔡章閣中學' },
    phones: ['+852 24520681'],
  },
  {
    district: '屯門區',
    code: '356',
    name: { enUS: 'CSBS MRS AW BOON HAW SECONDARY SCHOOL', zhHK: '鐘聲慈善社胡陳金枝中學' },
    phones: ['+852 24524688'],
  },
  {
    district: '屯門區',
    code: '357',
    name: { enUS: 'HO NGAI COLLEGE (SPONSORED BY SIK SIK YUEN)', zhHK: '嗇色園主辦可藝中學' },
    phones: ['+852 24417100'],
  },
  {
    district: '屯門區',
    code: '358',
    name: { enUS: 'CCC HOH FUK TONG COLLEGE', zhHK: '中華基督教會何福堂書院' },
    phones: ['+852 24596354'],
  },
  {
    district: '屯門區',
    code: '359',
    name: { enUS: 'JU CHING CHU SECONDARY SCHOOL (TUEN MUN)', zhHK: '裘錦秋中學（屯門）' },
    phones: ['+852 24611505'],
  },
  {
    district: '屯門區',
    code: '360',
    name: { enUS: 'PAOC KA CHI SECONDARY SCHOOL', zhHK: '加拿大神召會嘉智中學' },
    phones: ['+852 24413818'],
  },
  {
    district: '屯門區',
    code: '361',
    name: { enUS: 'LUI CHEUNG KWONG LUTHERAN COLLEGE', zhHK: '路德會呂祥光中學' },
    phones: ['+852 24503618'],
  },
  {
    district: '屯門區',
    code: '362',
    name: { enUS: 'MADAM LAU KAM LUNG SECONDARY SCHOOL OF MFBM', zhHK: '妙法寺劉金龍中學' },
    phones: ['+852 24619566'],
  },
  {
    district: '屯門區',
    code: '363',
    name: { enUS: 'CARITAS TUEN MUN MARDEN FOUNDATION SECONDARY SCHOOL', zhHK: '明愛屯門馬登基金中學' },
    phones: ['+852 24610304'],
  },
  {
    district: '屯門區',
    code: '364',
    name: { enUS: 'PLK CENTENARY LI SHIU CHUNG MEMORIAL COLLEGE', zhHK: '保良局百周年李兆忠紀念中學' },
    phones: ['+852 24623945'],
  },
  {
    district: '屯門區',
    code: '365',
    name: { enUS: 'PLK TANG YUK TIEN COLLEGE', zhHK: '保良局董玉娣中學' },
    phones: ['+852 24631766'],
  },
  {
    district: '屯門區',
    code: '366',
    name: { enUS: 'SAN WUI COMMERCIAL SOCIETY SECONDARY SCHOOL', zhHK: '新會商會中學' },
    phones: ['+852 24632660'],
  },
  {
    district: '屯門區',
    code: '367',
    name: { enUS: 'SEMPLE MEMORIAL SECONDARY SCHOOL', zhHK: '深培中學' },
    phones: ['+852 24524702'],
  },
  {
    district: '屯門區',
    code: '369',
    name: { enUS: 'SOUTH TUEN MUN GOVERNMENT SECONDARY SCHOOL', zhHK: '南屯門官立中學' },
    phones: ['+852 24045506'],
  },
  {
    district: '屯門區',
    code: '370',
    name: { enUS: "SKH ST SIMON'S LUI MING CHOI SECONDARY SCHOOL", zhHK: '聖公會聖西門呂明才中學' },
    phones: ['+852 24598236', '+852 39567900'],
  },
  {
    district: '屯門區',
    code: '371',
    name: { enUS: 'STFA LEUNG KAU KUI COLLEGE', zhHK: '順德聯誼總會梁銶琚中學' },
    phones: ['+852 24580766'],
  },
  {
    district: '屯門區',
    code: '372',
    name: { enUS: 'STFA TAM PAK YU COLLEGE', zhHK: '順德聯誼總會譚伯羽中學' },
    phones: ['+852 24501402'],
  },
  {
    district: '屯門區',
    code: '373',
    name: { enUS: "TWGH SUN HOI DIRECTORS' COLLEGE", zhHK: '東華三院辛亥年總理中學' },
    phones: ['+852 24645220'],
  },
  {
    district: '屯門區',
    code: '374',
    name: { enUS: 'TWGH YAU TZE TIN MEMORIAL COLLEGE', zhHK: '東華三院邱子田紀念中學' },
    phones: ['+852 24652205'],
  },
  {
    district: '屯門區',
    code: '375',
    name: { enUS: 'BAPTIST WING LUNG SECONDARY SCHOOL', zhHK: '浸信會永隆中學' },
    phones: ['+852 24643638'],
  },
  {
    district: '屯門區',
    code: '376',
    name: { enUS: 'TSUNG TSIN COLLEGE', zhHK: '崇真書院' },
    phones: ['+852 24637373'],
  },
  {
    district: '屯門區',
    code: '377',
    name: { enUS: 'TUEN MUN CATHOLIC SECONDARY SCHOOL', zhHK: '屯門天主教中學' },
    phones: ['+852 24632082'],
  },
  {
    district: '屯門區',
    code: '378',
    name: { enUS: 'TUEN MUN GOVERNMENT SECONDARY SCHOOL', zhHK: '屯門官立中學' },
    phones: ['+852 24580459'],
  },
  {
    district: '屯門區',
    code: '379',
    name: { enUS: 'YOT CHAN WONG SUK FONG MEMORIAL SECONDARY SCHOOL', zhHK: '仁愛堂陳黃淑芳紀念中學' },
    phones: ['+852 24666802'],
  },
  {
    district: '屯門區',
    code: '380',
    name: { enUS: 'YAN CHAI HOSPITAL NO.2 SECONDARY SCHOOL', zhHK: '仁濟醫院第二中學' },
    phones: ['+852 24673736'],
  },
  {
    district: '屯門區',
    code: '381',
    name: { enUS: 'YAN OI TONG TIN KA PING SECONDARY SCHOOL', zhHK: '仁愛堂田家炳中學' },
    phones: ['+852 2464373'],
  },
  {
    district: '屯門區',
    code: '382',
    name: { enUS: 'YPI&CA LEE LIM MING COLLEGE', zhHK: '恩平工商會李琳明中學' },
    phones: ['+852 24670652 , +852 24618818'],
  },
  {
    district: '元朗區',
    code: '383',
    name: { enUS: 'BETHEL HIGH SCHOOL', zhHK: '伯特利中學' },
    phones: ['+852 24712622'],
  },
  {
    district: '元朗區',
    code: '384',
    name: { enUS: 'CARITAS YUEN LONG CHAN CHUN HA SECONDARY SCHOOL', zhHK: '明愛元朗陳震夏中學' },
    phones: ['+852 24755432'],
  },
  {
    district: '元朗區',
    code: '385',
    name: { enUS: 'CHIU LUT SAU MEMORIAL SECONDARY SCHOOL', zhHK: '趙聿修紀念中學' },
    phones: ['+852 24778237'],
  },
  {
    district: '元朗區',
    code: '386',
    name: { enUS: 'CUHK FAA THOMAS CHEUNG SECONDARY SCHOOL', zhHK: '香港中文大學校友會聯會張煊昌中學' },
    phones: ['+852 24483111'],
  },
  {
    district: '元朗區',
    code: '387',
    name: { enUS: 'GERTRUDE SIMON LUTHERAN COLLEGE', zhHK: '路德會西門英才中學' },
    phones: ['+852 24782424'],
  },
  {
    district: '元朗區',
    code: '388',
    name: { enUS: 'HO DAO COLLEGE (SPONSORED BY SIK SIK YUEN)', zhHK: '可道中學（嗇色園主辦）' },
    phones: ['+852 24799885'],
  },
  {
    district: '元朗區',
    code: '389',
    name: { enUS: 'JU CHING CHU SECONDARY SCHOOL (YUEN LONG)', zhHK: '裘錦秋中學（元朗）' },
    phones: ['+852 24450228'],
  },
  {
    district: '元朗區',
    code: '390',
    name: { enUS: 'CCC KEI LONG COLLEGE', zhHK: '中華基督教會基朗中學' },
    phones: ['+852 24754781'],
  },
  {
    district: '元朗區',
    code: '391',
    name: { enUS: 'CCC KEI YUEN COLLEGE', zhHK: '中華基督教會基元中學' },
    phones: ['+852 24750331'],
  },
  {
    district: '元朗區',
    code: '392',
    name: { enUS: 'TYYI MFBM NEI MING CHAN LCT MEM COLLEGE', zhHK: '圓玄學院妙法寺內明陳呂重德紀念中學' },
    phones: ['+852 24458899'],
  },
  {
    district: '元朗區',
    code: '394',
    name: { enUS: 'NTHYK YUEN LONG DISTRICT SECONDARY SCHOOL', zhHK: '新界鄉議局元朗區中學' },
    phones: ['+852 24766226'],
  },
  {
    district: '元朗區',
    code: '395',
    name: { enUS: 'PAK KAU COLLEGE', zhHK: '伯裘書院' },
    phones: ['+852 24482960'],
  },
  {
    district: '元朗區',
    code: '397',
    name: { enUS: 'POH TANG PUI KING MEMORIAL COLLEGE', zhHK: '博愛醫院鄧佩瓊紀念中學' },
    phones: ['+852 24741576'],
  },
  {
    district: '元朗區',
    code: '398',
    name: { enUS: 'PUI SHING CATHOLIC SECONDARY SCHOOL', zhHK: '天主教培聖中學' },
    phones: ['+852 24450800'],
  },
  {
    district: '元朗區',
    code: '399',
    name: { enUS: "QES OLD STUDENTS' ASSOCIATION SECONDARY SCHOOL", zhHK: '伊利沙伯中學舊生會中學' },
    phones: ['+852 23386122'],
  },
  {
    district: '元朗區',
    code: '400',
    name: { enUS: 'SKH BISHOP BAKER SECONDARY SCHOOL', zhHK: '聖公會白約翰會督中學' },
    phones: ['+852 24754778'],
  },
  {
    district: '元朗區',
    code: '401',
    name: { enUS: 'SPHRC KUNG YIK SHE SECONDARY SCHOOL', zhHK: '十八鄉鄉事委員會公益社中學' },
    phones: ['+852 24478123'],
  },
  {
    district: '元朗區',
    code: '402',
    name: { enUS: 'SHUNG TAK CATHOLIC ENGLISH COLLEGE', zhHK: '天主教崇德英文書院' },
    phones: ['+852 24764263'],
  },
  {
    district: '元朗區',
    code: '403',
    name: { enUS: 'TWGHs KWOK YAT WAI COLLEGE', zhHK: '東華三院郭一葦中學' },
    phones: ['+852 24471258'],
  },
  {
    district: '元朗區',
    code: '404',
    name: { enUS: 'TWGH LO KON TING MEMORIAL COLLEGE', zhHK: '東華三院盧幹庭紀念中學' },
    phones: ['+852 24742678'],
  },
  {
    district: '元朗區',
    code: '405',
    name: { enUS: 'HKMA K S LO COLLEGE', zhHK: '香港管理專業協會羅桂祥中學' },
    phones: ['+852 24703363'],
  },
  {
    district: '元朗區',
    code: '406',
    name: { enUS: 'TIN SHUI WAI GOVERNMENT SECONDARY SCHOOL', zhHK: '天水圍官立中學' },
    phones: ['+852 24450967'],
  },
  {
    district: '元朗區',
    code: '407',
    name: { enUS: 'ELCHK YL LUTHERAN SECONDARY SCHOOL', zhHK: '基督教香港信義會元朗信義中學' },
    phones: ['+852 24480622'],
  },
  {
    district: '元朗區',
    code: '408',
    name: { enUS: 'YUEN LONG MERCHANTS ASSOCIATION SECONDARY SCHOOL', zhHK: '元朗商會中學' },
    phones: ['+852 24787348'],
  },
  {
    district: '元朗區',
    code: '410',
    name: { enUS: 'YUEN LONG PUBLIC SECONDARY SCHOOL', zhHK: '元朗公立中學' },
    phones: ['+852 24762357'],
  },
  {
    district: '元朗區',
    code: '411',
    name: {
      enUS: 'HHCKLA BUDDHIST MA KAM CHAN MEMORIAL ENGLISH SEC SCH',
      zhHK: '香海正覺蓮社佛教馬錦燦紀念英文中學',
    },
    phones: ['+852 26699208'],
  },
  {
    district: '北區',
    code: '412',
    name: { enUS: 'CARITAS FANLING CHAN CHUN HA SECONDARY SCHOOL', zhHK: '明愛粉嶺陳震夏中學' },
    phones: ['+852 26699966'],
  },
  {
    district: '北區',
    code: '413',
    name: { enUS: 'DE LA SALLE SECONDARY SCHOOL NT', zhHK: '新界喇沙中學' },
    phones: ['+852 26700443'],
  },
  {
    district: '北區',
    code: '414',
    name: { enUS: 'FANLING GOVERNMENT SECONDARY SCHOOL', zhHK: '粉嶺官立中學' },
    phones: ['+852 26776778'],
  },
  {
    district: '北區',
    code: '415',
    name: { enUS: 'FANLING LUTHERAN SECONDARY SCHOOL', zhHK: '基督教香港信義會心誠中學' },
    phones: ['+852 26700541'],
  },
  {
    district: '北區',
    code: '416',
    name: { enUS: 'FUNG KAI LIU MAN SHEK TONG SECONDARY SCHOOL', zhHK: '鳳溪廖萬石堂中學' },
    phones: ['+852 26736106'],
  },
  {
    district: '北區',
    code: '417',
    name: { enUS: 'FUNG KAI NO.1 SECONDARY SCHOOL', zhHK: '鳳溪第一中學' },
    phones: ['+852 26700366'],
  },
  {
    district: '北區',
    code: '419',
    name: { enUS: 'HKTA TANG HIN MEMORIAL SECONDARY SCHOOL', zhHK: '香港道教聯合會鄧顯紀念中學' },
    phones: ['+852 26726820'],
  },
  {
    district: '北區',
    code: '420',
    name: { enUS: 'CCC KEI SAN SECONDARY SCHOOL', zhHK: '中華基督教會基新中學' },
    phones: ['+852 26693906'],
  },
  {
    district: '北區',
    code: '421',
    name: { enUS: 'PLK MA KAM MING COLLEGE', zhHK: '保良局馬錦明中學' },
    phones: ['+852 26794545'],
  },
  {
    district: '北區',
    code: '422',
    name: { enUS: 'SKH CHAN YOUNG SECONDARY SCHOOL', zhHK: '聖公會陳融中學' },
    phones: ['+852 26718989'],
  },
  {
    district: '北區',
    code: '424',
    name: { enUS: 'SHEUNG SHUI GOVERNMENT SECONDARY SCHOOL', zhHK: '上水官立中學' },
    phones: ['+852 26680628'],
  },
  {
    district: '北區',
    code: '425',
    name: { enUS: "ST FRANCIS OF ASSISI'S COLLEGE", zhHK: '聖芳濟各書院' },
    phones: ['+852 26779709'],
  },
  {
    district: '北區',
    code: '426',
    name: { enUS: "TWGH KAP YAN DIRECTORS' COLLEGE", zhHK: '東華三院甲寅年總理中學' },
    phones: ['+852 26727395'],
  },
  {
    district: '北區',
    code: '427',
    name: { enUS: 'TWGH LI KA SHING COLLEGE', zhHK: '東華三院李嘉誠中學' },
    phones: ['+852 26697455'],
  },
  {
    district: '北區',
    code: '428',
    name: { enUS: 'TIN KA PING SECONDARY SCHOOL', zhHK: '田家炳中學' },
    phones: ['+852 26731778'],
  },
  {
    district: '大埔區',
    code: '429',
    name: { enUS: 'AOG HEBRON SECONDARY SCHOOL', zhHK: '神召會康樂中學' },
    phones: ['+852 26520698'],
  },
  {
    district: '大埔區',
    code: '431',
    name: { enUS: 'BUDDHIST TAI KWONG CHI HONG COLLEGE', zhHK: '佛教大光慈航中學' },
    phones: ['+852 26640833'],
  },
  {
    district: '大埔區',
    code: '433',
    name: { enUS: 'CCC FUNG LEUNG KIT MEMORIAL SECONDARY SCHOOL', zhHK: '中華基督教會馮梁結紀念中學' },
    phones: ['+852 26516033'],
  },
  {
    district: '大埔區',
    code: '434',
    name: { enUS: 'CARMEL PAK U SECONDARY SCHOOL', zhHK: '迦密柏雨中學' },
    phones: ['+852 26650078'],
  },
  {
    district: '大埔區',
    code: '435',
    name: { enUS: 'CONFUCIAN TAI SHING HO KWOK PUI CHUN COLLEGE', zhHK: '孔教學院大成何郭佩珍中學' },
    phones: ['+852 26665926'],
  },
  {
    district: '大埔區',
    code: '436',
    name: { enUS: 'HKTA THE YUEN YUEN INST NO.2 SECONDARY SCHOOL', zhHK: '香港道教聯合會圓玄學院第二中學' },
    phones: ['+852 26616038'],
  },
  {
    district: '大埔區',
    code: '437',
    name: { enUS: 'HKRSS TAI PO SECONDARY SCHOOL', zhHK: '香港紅卍字會大埔卍慈中學' },
    phones: ['+852 26666821'],
  },
  {
    district: '大埔區',
    code: '438',
    name: { enUS: "HK TEACHERS' ASSN LEE HENG KWEI SECONDARY SCHOOL", zhHK: '香港教師會李興貴中學' },
    phones: ['+852 26432734'],
  },
  {
    district: '大埔區',
    code: '439',
    name: { enUS: 'SALEM-IMMANUEL LUTHERAN COLLEGE', zhHK: '南亞路德會沐恩中學' },
    phones: ['+852 26673129'],
  },
  {
    district: '大埔區',
    code: '440',
    name: { enUS: 'KAU YAN COLLEGE', zhHK: '救恩書院' },
    phones: ['+852 26608308'],
  },
  {
    district: '大埔區',
    code: '442',
    name: { enUS: 'NTHYK TAI PO DISTRICT SECONDARY SCHOOL', zhHK: '新界鄉議局大埔區中學' },
    phones: ['+852 26643032'],
  },
  {
    district: '大埔區',
    code: '443',
    name: { enUS: 'SKH BISHOP MOK SAU TSENG SECONDARY SCHOOL', zhHK: '聖公會莫壽增會督中學' },
    phones: ['+852 26567804'],
  },
  {
    district: '大埔區',
    code: '445',
    name: { enUS: 'TAI PO SAM YUK SECONDARY SCHOOL', zhHK: '大埔三育中學' },
    phones: ['+852 26653459'],
  },
  {
    district: '大埔區',
    code: '446',
    name: { enUS: 'VALTORTA COLLEGE', zhHK: '恩主教書院' },
    phones: ['+852 26560017'],
  },
  {
    district: '大埔區',
    code: '447',
    name: { enUS: 'WONG SHIU CHI SECONDARY SCHOOL', zhHK: '王肇枝中學' },
    phones: ['+852 26561270'],
  },
  {
    district: '沙田區',
    code: '448',
    name: { enUS: 'BAPTIST LUI MING CHOI SECONDARY SCHOOL', zhHK: '浸信會呂明才中學' },
    phones: ['+852 26922161'],
  },
  {
    district: '沙田區',
    code: '449',
    name: { enUS: 'BUDDHIST KOK KWONG SECONDARY SCHOOL', zhHK: '佛教覺光法師中學' },
    phones: ['+852 26473737'],
  },
  {
    district: '沙田區',
    code: '450',
    name: { enUS: 'BUDDHIST WONG WAN TIN COLLEGE', zhHK: '佛教黃允畋中學' },
    phones: ['+852 26058369', '+852 26052876'],
  },
  {
    district: '沙田區',
    code: '451',
    name: { enUS: 'CHINESE YMCA COLLEGE', zhHK: '青年會書院' },
    phones: ['+852 26419588'],
  },
  {
    district: '沙田區',
    code: '452',
    name: { enUS: 'CHIU CHOW ASSOCIATION SECONDARY SCHOOL', zhHK: '潮州會館中學' },
    phones: ['+852 26428383'],
  },
  {
    district: '沙田區',
    code: '453',
    name: { enUS: 'CHRIST COLLEGE', zhHK: '基督書院' },
    phones: ['+852 26353330'],
  },
  {
    district: '沙田區',
    code: '454',
    name: { enUS: 'CHRISTIAN ALLIANCE CHENG WING GEE COLLEGE', zhHK: '香港九龍塘基督教中華宣道會鄭榮之中學' },
    phones: ['+852 26049762'],
  },
  {
    district: '沙田區',
    code: '455',
    name: { enUS: 'GCC&ITKD LAU PAK LOK SECONDARY SCHOOL', zhHK: '東莞工商總會劉百樂中學' },
    phones: ['+852 26951336'],
  },
  {
    district: '沙田區',
    code: '456',
    name: { enUS: 'HELEN LIANG MEMORIAL SECONDARY SCHOOL (SHATIN)', zhHK: '梁文燕紀念中學（沙田）' },
    phones: ['+852 26941414'],
  },
  {
    district: '沙田區',
    code: '458',
    name: { enUS: 'IMMACULATE HEART OF MARY COLLEGE', zhHK: '聖母無玷聖心書院' },
    phones: ['+852 26471358'],
  },
  {
    district: '沙田區',
    code: '459',
    name: { enUS: 'KIANGSU-CHEKIANG COLLEGE (SHATIN)', zhHK: '沙田蘇浙公學' },
    phones: ['+852 26972179'],
  },
  {
    district: '沙田區',
    code: '460',
    name: { enUS: 'KWOK TAK SENG CATHOLIC SECONDARY SCHOOL', zhHK: '天主教郭得勝中學' },
    phones: ['+852 26059033'],
  },
  {
    district: '沙田區',
    code: '461',
    name: { enUS: 'LOCK TAO SECONDARY SCHOOL', zhHK: '樂道中學' },
    phones: ['+852 26021000'],
  },
  {
    district: '沙田區',
    code: '462',
    name: { enUS: 'LOK SIN TONG YOUNG KO HSIAO LIN SECONDARY SCHOOL', zhHK: '樂善堂楊葛小琳中學' },
    phones: ['+852 26056632'],
  },
  {
    district: '沙田區',
    code: '463',
    name: { enUS: "MA ON SHAN ST JOSEPH'S SECONDARY SCHOOL", zhHK: '馬鞍山聖若瑟中學' },
    phones: ['+852 26339913'],
  },
  {
    district: '沙田區',
    code: '464',
    name: { enUS: 'MA ON SHAN TSUNG TSIN SECONDARY SCHOOL', zhHK: '馬鞍山崇真中學' },
    phones: ['+852 26404938'],
  },
  {
    district: '沙田區',
    code: '465',
    name: { enUS: 'MA ON SHAN TSUNG TSIN SECONDARY SCHOOL', zhHK: '馬鞍山崇真中學' },
    phones: ['+852 26404938'],
  },
  {
    district: '沙田區',
    code: '466',
    name: { enUS: 'NG YUK SECONDARY SCHOOL', zhHK: '五育中學' },
    phones: ['+852 26921870'],
  },
  {
    district: '沙田區',
    code: '467',
    name: { enUS: 'PENTECOSTAL LAM HON KWONG SCHOOL', zhHK: '五旬節林漢光中學' },
    phones: ['+852 26488291'],
  },
  {
    district: '沙田區',
    code: '468',
    name: { enUS: 'PLK C W CHU COLLEGE', zhHK: '保良局朱敬文中學' },
    phones: ['+852 26991031'],
  },
  {
    district: '沙田區',
    code: '469',
    name: { enUS: 'PLK WU CHUNG COLLEGE', zhHK: '保良局胡忠中學' },
    phones: ['+852 26415866'],
  },
  {
    district: '沙田區',
    code: '470',
    name: { enUS: 'POK OI HOSPITAL CHAN KAI MEMORIAL COLLEGE', zhHK: '博愛醫院陳楷紀念中學' },
    phones: ['+852 26044118'],
  },
  {
    district: '沙田區',
    code: '471',
    name: { enUS: 'SHATIN PUI YING COLLEGE', zhHK: '沙田培英中學' },
    phones: ['+852 26917217'],
  },
  {
    district: '沙田區',
    code: '472',
    name: { enUS: 'SKH LAM KAU MOW SECONDARY SCHOOL', zhHK: '聖公會林裘謀中學' },
    phones: ['+852 26488222'],
  },
  {
    district: '沙田區',
    code: '473',
    name: { enUS: 'SKH TSANG SHIU TIM SECONDARY SCHOOL', zhHK: '聖公會曾肇添中學' },
    phones: ['+852 26975566'],
  },
  {
    district: '沙田區',
    code: '474',
    name: { enUS: 'SHA TIN GOVERNMENT SECONDARY SCHOOL', zhHK: '沙田官立中學' },
    phones: ['+852 26914744'],
  },
  {
    district: '沙田區',
    code: '475',
    name: { enUS: 'SHA TIN METHODIST COLLEGE', zhHK: '沙田官立沙田循道衞理中學中學' },
    phones: ['+852 26021300'],
  },
  {
    district: '沙田區',
    code: '476',
    name: { enUS: 'SHATIN TSUNG TSIN SECONDARY SCHOOL', zhHK: '沙田崇真中學' },
    phones: ['+852 26073881'],
  },
  {
    district: '沙田區',
    code: '479',
    name: { enUS: 'TWGH MRS FUNG WONG FUNG TING COLLEGE', zhHK: '東華三院馮黃鳳亭中學' },
    phones: ['+852 26913738'],
  },
  {
    district: '九龍城區',
    code: '480',
    name: { enUS: 'TWGH WONG FUNG LING COLLEGE', zhHK: '東華三院黃鳳翎中學' },
    phones: ['+852 26416238'],
  },
  {
    district: '沙田區',
    code: '481',
    name: { enUS: 'TWGH YOW KAM YUEN COLLEGE', zhHK: '東華三院邱金元中學' },
    phones: ['+852 26497385'],
  },
  {
    district: '九龍城區',
    code: '482',
    name: { enUS: 'HKCWC FUNG YIU KING MEMORIAL SECONDARY SCHOOL', zhHK: '香港中國婦女會馮堯敬紀念中學' },
    phones: ['+852 26404968'],
  },
  {
    district: '沙田區',
    code: '483',
    name: { enUS: 'TOI SHAN ASSOCIATION COLLEGE', zhHK: '台山商會中學' },
    phones: ['+852 26487871'],
  },
  {
    district: '沙田區',
    code: '484',
    name: { enUS: 'TSANG PIK SHAN SECONDARY SCHOOL', zhHK: '曾璧山中學' },
    phones: ['+852 26404933'],
  },
  {
    district: '沙田區',
    code: '485',
    name: { enUS: 'YCH TUNG CHI YING MEMORIAL SECONDARY SCHOOL', zhHK: '仁濟醫院董之英紀念中學' },
    phones: ['+852 26409822'],
  },
  {
    district: '西貢區',
    code: '486',
    name: { enUS: 'CARMEL DIVINE GRACE FOUNDATION SECONDARY SCHOOL', zhHK: '迦密主恩中學' },
    phones: ['+852 27010908'],
  },
  {
    district: '西貢區',
    code: '487',
    name: { enUS: 'CATHOLIC MING YUEN SECONDARY SCHOOL', zhHK: '天主教鳴遠中學' },
    phones: ['+852 27027102'],
  },
  {
    district: '西貢區',
    code: '488',
    name: { enUS: 'CHENG CHEK CHEE SECONDARY SCHOOL OF SK&HH DISTRICT NT', zhHK: '新界西貢坑口區鄭植之中學' },
    phones: ['+852 27198598'],
  },
  {
    district: '西貢區',
    code: '489',
    name: { enUS: 'KING LING COLLEGE', zhHK: '景嶺書院' },
    phones: ['+852 27029602'],
  },
  {
    district: '西貢區',
    code: '490',
    name: { enUS: 'PO LEUNG KUK HO YUK CHING (1984) COLLEGE', zhHK: '保良局甲子何玉清中學' },
    phones: ['+852 27037363'],
  },
  {
    district: '西貢區',
    code: '491',
    name: { enUS: 'HK AND MACAU LU CH QUEEN MAUD SECONDARY SCHOOL', zhHK: '港澳信義會慕德中學' },
    phones: ['+852 27026509'],
  },
  {
    district: '西貢區',
    code: '493',
    name: {
      enUS: 'SAI KUNG SUNG TSUN CATHOLIC SCHOOL (SECONDARY SECTION)',
      zhHK: '西貢崇真天主教學校（中學部）',
    },
    phones: ['+852 27921311', '+852 27926712'],
  },
  {
    district: '西貢區',
    code: '494',
    name: { enUS: 'TWGH LUI YUN CHOY MEMORIAL COLLEGE', zhHK: '東華三院呂潤財紀念中學' },
    phones: ['+852 27060743'],
  },
  {
    district: '西貢區',
    code: '495',
    name: { enUS: 'TSEUNG KWAN O GOVERNMENT SECONDARY SCHOOL', zhHK: '將軍澳官立中學' },
    phones: ['+852 27040051'],
  },
  {
    district: '西貢區',
    code: '496',
    name: { enUS: 'YCH LAN CHI PAT MEMORIAL SECONDARY SCHOOL', zhHK: '仁濟醫院靚次伯紀念中學' },
    phones: ['+852 27029033'],
  },
  {
    district: '離島區',
    code: '500',
    name: { enUS: 'CHEUNG CHAU GOVERNMENT SECONDARY SCHOOL', zhHK: '長洲官立中學' },
    phones: ['+852 29810514'],
  },
  {
    district: '屯門區',
    code: '503',
    name: { enUS: 'SMKMCF MA KO PAN MEMORIAL COLLEGE', zhHK: '馬錦明慈善基金馬可賓紀念中學' },
    phones: ['+852 24607704'],
  },
  {
    district: '東區',
    code: '504',
    name: { enUS: 'ISLAMIC KASIM TUET MEMORIAL COLLEGE', zhHK: '伊斯蘭脫維善紀念中學' },
    phones: ['+852 25709066'],
  },
  {
    district: '離島區',
    code: '505',
    name: {
      enUS: 'HO YU COLLEGE & PRIMARY SCHOOL (SPSD BY SIK SIK YUEN)',
      zhHK: '嗇色園主辦可譽中學暨可譽小學',
    },
    phones: ['+852 21091001'],
  },
  {
    district: '離島區',
    code: '506',
    name: { enUS: 'PLK MRS MA KAM MING - CHEUNG FOOK SIEN COLLEGE', zhHK: '保良局馬錦明夫人章馥仙中學' },
    phones: ['+852 21091133'],
  },
  {
    district: '西貢區',
    code: '507',
    name: { enUS: 'WEO CHANG PUI CHUNG MEMORIAL SCHOOL', zhHK: '威靈頓教育機構張沛松紀念中學' },
    phones: ['+852 27047002'],
  },
  {
    district: '西貢區',
    code: '508',
    name: { enUS: 'STFA CHENG YU TUNG SECONDARY SCHOOL', zhHK: '順德聯誼總會鄭裕彤中學' },
    phones: ['+852 21910291'],
  },
  {
    district: '西貢區',
    code: '511',
    name: { enUS: 'HKTA THE YUEN YUEN INSTITUTE NO.3 SECONDARY SCHOOL', zhHK: '香港道教聯合會圓玄學院第三中學' },
    phones: ['+852 21783223'],
  },
  {
    district: '西貢區',
    code: '512',
    name: { enUS: 'BUDDHIST MAU FUNG MEMORIAL COLLEGE', zhHK: '馬錦明慈善基金馬陳端喜紀念中學' },
    phones: ['+852 27067477'],
  },
  {
    district: '元朗區',
    code: '513',
    name: { enUS: 'MKMCF MA CHAN DUEN HEY MEMORIAL COLLEGE', zhHK: '佛教茂峰法師紀念中學' },
    phones: ['+852 24457171'],
  },
  {
    district: '北區',
    code: '514',
    name: { enUS: 'CHRISTIAN ALLIANCE S W CHAN MEMORIAL COLLEGE', zhHK: '宣道會陳朱素華紀念中學' },
    phones: ['+852 26709229'],
  },
  {
    district: '油尖旺區',
    code: '515',
    name: { enUS: 'SIR ELLIS KADOORIE SECONDARY SCHOOL (WEST KLN)', zhHK: '官立嘉道理爵士中學（西九龍）' },
    phones: ['+852 25761871'],
  },
  {
    district: '大埔區',
    code: '516',
    name: { enUS: 'CARMEL HOLY WORD SECONDARY SCHOOL', zhHK: '迦密聖道中學' },
    phones: ['+852 26539786'],
  },
  {
    district: '東區',
    code: '517',
    name: { enUS: 'FUKIEN SECONDARY SCHOOL (SIU SAI WAN)', zhHK: '福建中學（小西灣）' },
    phones: ['+852 25669223'],
  },
  {
    district: '東區',
    code: '518',
    name: { enUS: 'CHINA HOLINESS CHURCH LIVING SPIRIT COLLEGE', zhHK: '中華聖潔會靈風中學' },
    phones: ['+852 29589694'],
  },
  {
    district: '東區',
    code: '520',
    name: { enUS: 'KIANGSU-CHEKIANG COLLEGE', zhHK: '蘇浙公學' },
    phones: ['+852 29693969'],
  },
  {
    district: '東區',
    code: '521',
    name: { enUS: 'PUI KIU MIDDLE SCHOOL', zhHK: '培僑中學' },
    phones: ['+852 25662317'],
  },
  {
    district: '東區',
    code: '522',
    name: { enUS: 'HON WAH COLLEGE', zhHK: '漢華中學' },
    phones: ['+852 28171746'],
  },
  {
    district: '九龍城區',
    code: '523',
    name: { enUS: 'SCIENTIA SECONDARY SCHOOL', zhHK: '創知中學' },
    phones: ['+852 27144115'],
  },
  {
    district: '深水埗區',
    code: '524',
    name: { enUS: 'HEUNG TO MIDDLE SCHOOL', zhHK: '香島中學' },
    phones: ['+852 27790182'],
  },
  {
    district: '東區',
    code: '530',
    name: { enUS: 'MUNSANG COLLEGE (HONG KONG ISLAND)', zhHK: '港島民生書院' },
    phones: ['+852 25671666'],
  },
  {
    district: '元朗區',
    code: '531',
    name: { enUS: 'THE JOCKEY CLUB EDUYOUNG COLLEGE', zhHK: '賽馬會毅智書院' },
    phones: ['+852 24472322'],
  },
  {
    district: '東區',
    code: '532',
    name: { enUS: 'CNEC LAU WING SANG SECONDARY SCHOOL', zhHK: '中華傳道會劉永生中學' },
    phones: ['+852 27156333'],
  },
  {
    district: '東區',
    code: '533',
    name: { enUS: 'NLSI PEACE EVANGELICAL SECONDARY SCHOOL', zhHK: '新生命教育協會平安福音中學' },
    phones: ['+852 24401828'],
  },
  {
    district: '元朗區',
    code: '534',
    name: { enUS: 'YLPMSAA TANG SIU TONG SECONDARY SCHOOL', zhHK: '元朗公立中學校友會鄧兆棠中學' },
    phones: ['+852 24461661'],
  },
  {
    district: '元朗區',
    code: '535',
    name: { enUS: 'FANLING RHENISH CHURCH SECONDARY SCHOOL', zhHK: '粉嶺禮賢會中學' },
    phones: ['+852 29473698'],
  },
  {
    district: '大埔區',
    code: '536',
    name: { enUS: 'LING LIANG CHURCH M H LAU SECONDARY SCHOOL', zhHK: '靈糧堂劉梅軒中學' },
    phones: ['+852 26531234'],
  },
  {
    district: '西貢區',
    code: '537',
    name: { enUS: 'C&MA SUN KEI SECONDARY SCHOOL', zhHK: '基督教宣道會宣基中學' },
    phones: ['+852 21916022'],
  },
  {
    district: '西貢區',
    code: '538',
    name: { enUS: 'YCH WONG WHA SAN SECONDARY SCHOOL', zhHK: '仁濟醫院王華湘中學' },
    phones: ['+852 27060477'],
  },
  {
    district: '西貢區',
    code: '539',
    name: { enUS: 'POH 80TH ANNIVERSARY TANG YING HEI COLLEGE', zhHK: '博愛醫院八十週年鄧英喜中學' },
    phones: ['+852 22463221'],
  },
  {
    district: '北區',
    code: '540',
    name: { enUS: 'FANLING KAU YAN COLLEGE', zhHK: '粉嶺救恩書院' },
    phones: ['+852 21444545'],
  },
  {
    district: '屯門區',
    code: '542',
    name: { enUS: 'CHING CHUNG HAU PO WOON SECONDARY SCHOOL', zhHK: '青松侯寶垣中學' },
    phones: ['+852 24577154'],
  },
  {
    district: '沙田區',
    code: '543',
    name: { enUS: 'CUHKFAA CHAN CHUN HA SECONDARY SCHOOL', zhHK: '香港中文大學校友會聯會陳震夏中學' },
    phones: ['+852 26305006'],
  },
  {
    district: '觀塘區',
    code: '544',
    name: { enUS: 'PO CHIU CATHOLIC SECONDARY SCHOOL', zhHK: '天主教普照中學' },
    phones: ['+852 23479907'],
  },
  {
    district: '離島區',
    code: '548',
    name: { enUS: 'TUNG CHUNG CATHOLIC SCHOOL', zhHK: '東涌天主教學校' },
    phones: ['+852 21210884'],
  },
  {
    district: '西貢區',
    code: '549',
    name: { enUS: 'PO KOK SECONDARY SCHOOL', zhHK: '寶覺中學' },
    phones: ['+852 27022863'],
  },
  {
    district: '元朗區',
    code: '553',
    name: { enUS: 'TIN SHUI WAI METHODIST COLLEGE', zhHK: '天水圍循道衞理中學' },
    phones: ['+852 31562500'],
  },
  {
    district: '元朗區',
    code: '554',
    name: { enUS: 'STFA YUNG YAU COLLEGE', zhHK: '順德聯誼總會翁祐中學' },
    phones: ['+852 31570632'],
  },
  {
    district: '元朗區',
    code: '555',
    name: { enUS: 'HEUNG TO MIDDLE SCHOOL (TIN SHUI WAI)', zhHK: '天水圍香島中學' },
    phones: ['+852 26500016'],
  },
  {
    district: '黃大仙區',
    code: '556',
    name: { enUS: 'PLK CELINE HO YAM TONG COLLEGE', zhHK: '保良局何蔭棠中學' },
    phones: ['+852 26269930'],
  },
  {
    district: '觀塘區',
    code: '557',
    name: { enUS: 'YCH LAW CHAN CHOR SI COLLEGE', zhHK: '仁濟醫院羅陳楚思中學' },
    phones: ['+852 26821315'],
  },
  {
    district: '南區',
    code: '559',
    name: { enUS: 'HONG KONG SEA SCHOOL', zhHK: '香港航海學校' },
    phones: ['+852 28131561'],
  },
  {
    district: '深水埗區',
    code: '560',
    name: { enUS: 'CCC MING YIN PO LEUNG KUK TONG NAI KAN JUNIOR SECONDARY COLLEGE', zhHK: '保良局唐乃勤初中書院' },
    phones: ['+852 21945707'],
  },
  {
    district: '元朗區',
    code: '561',
    name: { enUS: 'TWGH CY MA MEMORIAL COLLEGE', zhHK: '元朗天主教中學' },
    phones: ['+852 24439833'],
  },
  {
    district: '元朗區',
    code: '562',
    name: { enUS: 'YUEN LONG CATHOLIC SECONDARY SCHOOL', zhHK: '東華三院馬振玉紀念中學' },
    phones: ['+852 24431363'],
  },
  {
    district: '沙田區',
    code: '563',
    name: { enUS: 'CARITAS MA ON SHAN SECONDARY SCHOOL', zhHK: '明愛馬鞍山中學' },
    phones: ['+852 26419733'],
  },
  {
    district: '離島區',
    code: '564',
    name: { enUS: 'LING LIANG CHURCH E WUN SECONDARY SCHOOL', zhHK: '靈糧堂怡文中學' },
    phones: ['+852 21094000'],
  },
  {
    district: '北區',
    code: '565',
    name: { enUS: 'ELEGANTIA COLLEGE (SPONSORED BY EDUCATION CONVERGENCE)', zhHK: '風采中學（教育評議會主辦）' },
    phones: ['+852 24683680'],
  },
  {
    district: '元朗區',
    code: '566',
    name: { enUS: 'CCC FONG YUN WAH SECONDARY SCHOOL', zhHK: '中華基督教會方潤華中學' },
    phones: ['+852 24455833'],
  },
  {
    district: '大埔區',
    code: '567',
    name: { enUS: 'HK&KLN KFWA SUN FONG CHUNG COLLEGE', zhHK: '港九街坊婦女會孫方中書院' },
    phones: ['+852 26567123'],
  },
  {
    district: '九龍城區',
    code: '568',
    name: { enUS: 'CCC KEI TO SECONDARY SCHOOL', zhHK: '中華基督教會基道中學' },
    phones: ['+852 26271028'],
  },
  {
    district: '西貢區',
    code: '575',
    name: { enUS: 'HHCKLA BUDDHIST CHING KOK SECONDARY SCHOOL', zhHK: '香海正覺蓮社佛教正覺中學' },
    phones: ['+852 22463383'],
  },
  {
    district: '西貢區',
    code: '576',
    name: { enUS: 'HEUNG TO SECONDARY SCHOOL (TSEUNG KWAN O)', zhHK: '將軍澳香島中學' },
    phones: ['+852 26233039'],
  },
  {
    district: '離島區',
    code: '578',
    name: { enUS: 'HKFEW WONG CHO BAU SECONDARY SCHOOL', zhHK: '香港教育工作者聯會黃楚標中學' },
    phones: ['+852 21094005'],
  },
  {
    district: '元朗區',
    code: '583',
    name: { enUS: 'QESOSA TONG KWOK WAH SECONDARY SCHOOL', zhHK: '伊利沙伯中學舊生會湯國華中學' },
    phones: ['+852 26175000'],
  },
  {
    district: '元朗區',
    code: '585',
    name: { enUS: 'CUMBERLAND PRESBYTERIAN CHURCH YAO DAO SEC SCH', zhHK: '金巴崙長老會耀道中學' },
    phones: ['+852 24730777'],
  },
];

export const tertiarySchools: SchoolData[] = [
  {
    district: '九龍城區',
    code: 'CITYU',
    name: { enUS: 'City University of Hong Kong', zhHK: '香港城市大學' },
    website: 'https://www.cityu.edu.hk',
  },
  {
    district: '黃大仙區',
    code: 'HKBU',
    name: { enUS: 'Hong Kong Baptist University', zhHK: '香港浸會大學' },
    website: 'https://www.hkbu.edu.hk',
  },
  {
    district: '屯門區',
    code: 'LM',
    name: { enUS: 'Lingnan University', zhHK: '嶺南大學' },
    website: 'https://www.ln.edu.hk',
  },
  {
    district: '沙田區',
    code: 'CUHK',
    name: { enUS: 'The Chinese University of Hong Kong', zhHK: '香港中文大學' },
    website: 'https://www.cuhk.edu.hk',
  },
  {
    district: '大埔區',
    code: 'EDUHK',
    name: { enUS: 'The Education University of Hong Kong', zhHK: '香港教育大學' },
    website: 'https://www.eduhk.hk',
  },
  {
    district: '油尖旺區',
    code: 'PLOYU',
    name: { enUS: 'The Hong Kong Polytechnic University', zhHK: '香港理工大學' },
    website: 'https://www.polyu.edu.hk',
  },
  {
    district: '西貢區',
    code: 'HKUST',
    name: { enUS: 'The Hong Kong University of Science and Technology', zhHK: '香港科技大學' },
    website: 'https://hkust.edu.hk',
  },
  {
    district: '中西區',
    code: 'HKU',
    name: { enUS: 'The Hong Kong University', zhHK: '香港大學' },
    website: 'https://www.hku.hk',
  },
];
